---
- name: Install murmur
  apt:
    name="mumble-server"

- name: Copy default
  template:
    src="default.j2"
    dest="/etc/default/mumble-server"
    owner="root"
    group="root"
    mode="0644"
  notify:
    - "restart murmur"

- name: Copy configuration
  template:
    src="mumble-server.ini.j2"
    dest="/etc/mumble-server.ini"
    owner="root"
    group="mumble-server"
    mode="0640"
  notify:
    - "restart murmur"

- name: Start server
  service:
    name="mumble-server"
    state="started"

- name: Set SuperUser password
  no_log: true
  command: murmurd -ini /etc/mumble-server.ini -supw "{{murmur_superuser_password}}"
