---
- name: Install murmur
  apt:
    name="mumble-server"

- name: Copy configuration
  template:
    src="mumble-server.ini.j2"
    dest="/etc/mumble-server.ini"
    owner="root"
    group="mumble-server"
    mode="0640"
  notify:
    - "restart murmur"
